import {
    TrendingUp,
    Building2,
    Calculator,
    Globe,
    ShoppingCart,
    Briefcase,
    BarChart3,
    DollarSign,
    Plane,
    Package,
    Landmark,
    BookOpen,
    GraduationCap,
    Store,
    Scale,
    LineChart,
    Wallet,
    UtensilsCrossed,
    Network,
    FileText,
    Shield,
    Sparkles,
    Handshake,
    Target,
    type LucideIcon,
} from "lucide-react";

export const PROGRAM_ICON_MAP: Record<string, LucideIcon> = {
    TrendingUp,
    Building2,
    Calculator,
    Globe,
    ShoppingCart,
    Briefcase,
    BarChart3,
    DollarSign,
    Plane,
    Package,
    Landmark,
    BookOpen,
    GraduationCap,
    Store,
    Scale,
    LineChart,
    Wallet,
    UtensilsCrossed,
    Network,
    FileText,
    Shield,
    Sparkles,
    Handshake,
    Target,
};

export function getProgramIcon(iconName: string): LucideIcon {
    return PROGRAM_ICON_MAP[iconName] ?? BookOpen;
}
