/** English fallbacks — University → Famous graduates (`topNav`). */

export const FAMOUS_GRADUATES_PAGE_DEFAULTS = {
  famousGraduatesPageTitle: "Famous graduates",
  famousGraduatesPageIntro:
    "Alumni of Termez University of Economics and Service recognized for their achievements and contributions.",
  famousGraduatesReadMore: "Read more",
} as const;

export type FamousGraduateDetailBioKey = keyof typeof FAMOUS_GRADUATE_DETAIL_DEFAULTS;

/** Biography blocks — paragraphs separated by `\n\n` for splitting in the UI. */
export const FAMOUS_GRADUATE_DETAIL_DEFAULTS = {
  famousGraduateDetailBegaliyevAzamBody:
    "Born on February 29, 1988, in Jarkurgan district. He received his higher education at Termez State University. In 2025, he completed his master’s degree at Termez University of Economics and Service, specializing as an economist (researcher-pedagogue).\n\nThroughout his career, Begaliyev A\u2019zam Olimnazarovich has worked effectively in the field of education. Since 2010, he has held various positions at the Termez College of Economics and the Termez College of Transport and Services. Serving as a teacher, department head, and acting director, he made a significant contribution to the education and professional training of young people.\n\nFrom 2018, A\u2019zam Olimnazarovich has been engaged in leadership activities. Between 2020 and 2025, he served as the director of Vocational School No. 2 in Jarkurgan district. Since 2025, he has been working as the director of Polytechnic No. 2 in Jarkurgan district, Surkhandarya region.\n\nFor his dedicated service and contribution to the field of education, he was awarded the honorary badge “Excellence in Secondary Specialized and Professional Education.”",
  famousGraduateDetailPanjievaNigoraBody:
    "Panjieva Nigora Normakhmatovna is a responsible and experienced specialist who has earned a respectable place in the energy sector of Surkhandarya region and is recognized as one of the leading professionals in the field of accounting.\n\nShe was born on February 14, 1979, in Termez city, Surkhandarya region. In 2001, she graduated from the full-time program of Termez State University with a degree in Management. In 2025, she completed her master’s degree in Economics at Termez University of Economics and Service.\n\nNigora Normakhmatovna began her professional career in 2002 as an economist and, within a short period, gained strong knowledge and valuable experience in her field. Afterwards, she worked successfully in various positions within the Surkhandarya Territorial Electric Networks system. Since 2016, she has been serving as Chief Accountant, actively contributing to the modernization of accounting practices.\n\nSince 2023, she has been working as the Chief Accountant of the Central Accounting Department at the Surkhandarya regional branch of JSC “Regional Electric Networks.”\n\nPanjieva Nigora Normakhmatovna has earned the respect of her colleagues for her honesty, precision, and responsibility in the field of accounting and economics. Her commitment to work and strong leadership skills have significantly contributed to increasing efficiency in the sector.",
  famousGraduateDetailAlimovJalolBody:
    "Alimov Jalol Qudratovich was born on March 26, 1972, in Muzrabot district. In 2002, he graduated from Termez State University, and in 2006, from Samarkand State University, specializing in Macroeconomics and Law. In 2025, he completed his master’s degree in Economics at Termez University of Economics and Service.\n\nHe began his professional career in 1988 as a brigade leader in a youth production brigade. Later, he worked as an accountant and worker in trade enterprises, a court executor, and held responsible positions in the prosecutor’s office and courts. At the same time, he gained significant experience in the banking sector, working as a chief legal counsel in various branches.\n\nSince 2014, Alimov Jalol Qudratovich has served in the system of the Central Bank of the Republic of Uzbekistan, holding the position of Chief Legal Adviser under the leadership of the Surkhandarya Regional Main Department. In 2025, he was appointed Chief Legal Counsel of the Litigation and Coordination of Legal Advisers of Regional Main Departments Division within the Legal Department of the Central Bank.\n\nOver the course of more than 35 years of professional activity, Jalol Qudratovich has accumulated vast experience in the legal field and has earned high recognition as a responsible and proactive specialist.",
  famousGraduateDetailAbdirakhmanovKhayitaliBody:
    "He was born on May 30, 1993, in Jarkurgan district, Surkhandarya region. In 2016, he successfully graduated from Termez State University, and in 2024 — from Termez University of Economics and Service, specializing in finance and economics.\n\nHis career began in 2016 at the Asakabank system, where he quickly demonstrated efficiency in various fields. With experience in lending, business support, and retail services, he has worked in responsible positions and established himself as a qualified specialist.\n\nFrom 2019 to 2023, he worked effectively in the corporate and retail service departments of the bank as a leading specialist and head of department. Since 2024, he has been serving as Deputy Manager of the Termez branch of Asakabank JSC.\n\nAbdirakhmanov Khayitali Normukhammadovich has earned respect in his team through his consistent career path, initiative, and responsible working style. His main goal is to improve the efficiency of providing the population and clients with convenient, modern, and reliable banking services.",
  famousGraduateDetailAshurovKaromatBody:
    "He was born on October 13, 1979, in Qiziriq district, Surkhandarya region. Married, father of three children.\n\nFrom 1986 to 1996, he studied at Secondary School No. 8. In 2000, he graduated from Termez State University, and in 2003 — from Tashkent State University of Economics. In 2024, he successfully completed his master’s degree in Economics at Termez University of Economics and Service. His specialization is teaching and finance.\n\nHe began his career in 2000 as a teacher. From 2003 to 2019, he held various managerial positions in Surkhandarya region. Since July 2019, he has been serving as Deputy Mayor of Termez city for youth policy, social development, and spiritual-enlightenment affairs.\n\nThroughout his career, he has implemented numerous innovations and reforms in the field of education and youth policy. He ensured the first-ever participation of regional students in international olympiads and achieved high results in science and sports. In 2019, he established the non-governmental educational institutions “Children’s Academy Termez” and “Smart Children of Termez.” He contributed to increasing preschool education coverage to 55.9% and reducing crime rates.\n\nHe has earned respect as a skilled organizer, an initiative-driven and demanding leader. His students are now serving the development of the country across various fields.",
  famousGraduateDetailTogayevRakhmatilloBody:
    "He was born on October 3, 1987, in Sariosiyo district of Surkhandarya region. From an early age, he was fond of art and actively engaged in social life, combining his studies with community activities.\n\nIn 2011, he graduated from the full-time department of Termez State University with a degree in Music Education. Later, in 2023, he completed the part-time program at the same university, specializing in Economics by sectors and industries. In 2025, he successfully obtained his master’s degree in Economics from Termez University of Economics and Service.\n\nTogayev Rakhmatillo Ravzatovich began his professional career during his student years. From 2009 to 2010, he worked as an accountant at Preschool Educational Institution No. 12 in Termez district. Between 2011 and 2017, he served as Head of the Department of Culture and Enlightenment at the Surkhandarya Regional Council of the “Kamolot” Youth Social Movement, Chairman of the Uzun District Council, as well as Head of a department of the regional council and Chairman of the district council.\n\nFrom 2019 to 2021, he worked as Deputy Hokim of Uzun district for Youth Policy, Social Development, and Spiritual-Enlightenment Affairs. During this period, he implemented numerous initiatives to ensure youth employment, organize meaningful leisure activities, and strengthen their spiritual upbringing.\n\nIn 2021, he served as Deputy Chairman of the Surkhandarya Regional Council of UzMTDP for Ideological Affairs and Information Policy. In the same year, he also worked as Chief Specialist for Cooperation with Religious Organizations at the Surkhandarya Regional Department of the Committee on Religious Affairs.\n\nSince 2024, he has been serving as Deputy Hokim of Termez district for Youth Policy, Social Development, and Spiritual-Enlightenment Affairs.",
  famousGraduateDetailSadatovOltiboyBody:
    "Born on August 23, 1976, in Sherobod district, Surkhandarya region. From an early age, his personal qualities such as a passion for knowledge, diligence, and initiative were evident. In 2006, he graduated in absentia from Karshi State University with a degree in socio-economic studies. In 2025, he successfully completed his Master’s degree in Economics at the Termez University of Economics and Service.\n\nFrom 1995 to 1998, he worked as a private entrepreneur. Since 1998, he continued his career in the education sector. He first served as Deputy Director for administrative affairs and an accountant at the Specialized Boarding Lyceum for Gifted Children No. 17 in Termez district. Between 2009 and 2011, he worked as Chief Accountant at the Termez District Statistics Department and at the Termez Pedagogical College. During this time, he stood out for his accuracy in accounting, responsibility, and systematic approach.\n\nFrom 2011 to 2018, he worked as Chief Accountant and Economics teacher at the Termez College of Preschool Education and Service. There he not only managed financial matters but also taught economics to young students, contributing to their professional training.\n\nIn 2018, he was appointed Director of the same college and effectively managed the institution for one year. From 2019 onwards, Sadatov Oltiboy Nazarovich headed the Termez City Department of Public Education of Surkhandarya region, where he implemented wide-scale efforts to improve the quality of education, strengthen the material and technical base of schools, and raise teachers’ qualifications.\n\nSince 2023, he has been serving as the Head of the Boysun District Department of Preschool and School Education. In this position, he has focused on improving the quality of the education system, creating favorable conditions for children’s all-round development, and enhancing the potential of pedagogical staff.\n\nOver nearly 30 years of professional activity, Oltiboy Nazarovich has progressed from financial management in the education system to high-level leadership positions. Thanks to his experience, responsibility, and dedication to education, he is recognized today as one of the leaders making a valuable contribution to the development of the education system in Surkhandarya.",
  famousGraduateDetailIbragimovRustamBody:
    "Born on April 16, 1981, in Denau region. In 2002, he graduated from Termez State University; in 2006, from Tashkent State Law Institute; and in 2025, he completed a master’s degree at Termez University of Economics and Service, specializing in Public Finance and International Finance. His professional background covers banking, law, and finance-economics.\n\nHe began his career in 2004 as a lawyer. Later, he served in the prosecution system in various positions, including senior inspector, investigator, and department prosecutor.\n\nFrom 2019 to 2021, he worked as an investigator at the Department for Investigating Especially Serious Crimes under the General Prosecutor’s Office. From 2022 to 2025, he headed the Department for Combating Organized Crime and Corruption at the Surkhandarya Regional Prosecutor’s Office.\n\nSince 2025, Rustam Alijanovich has been serving as the Prosecutor of Termez city. He holds the rank of Junior Counselor of Justice.\n\nWith his professional experience and expertise, he is recognized as a highly qualified specialist effectively serving in law enforcement agencies.",
} as const;

/** Maps graduate `id` to `topNav` bio key (detail pages only). */
export const FAMOUS_GRADUATE_DETAIL_BIO_KEY_BY_ID: Partial<
  Record<string, FamousGraduateDetailBioKey>
> = {
  "begaliyev-azam-olimnazarovich": "famousGraduateDetailBegaliyevAzamBody",
  "panjieva-nigora-normakhmatovna": "famousGraduateDetailPanjievaNigoraBody",
  "alimov-jalol-qudratovich": "famousGraduateDetailAlimovJalolBody",
  "abdirakhmanov-khayitali-normukhammadovich": "famousGraduateDetailAbdirakhmanovKhayitaliBody",
  "ashurov-karomat-musulmonqulovich": "famousGraduateDetailAshurovKaromatBody",
  "togayev-rakhmatillo-ravzatovich": "famousGraduateDetailTogayevRakhmatilloBody",
  "sadatov-oltiboy-nazarovich": "famousGraduateDetailSadatovOltiboyBody",
  "ibragimov-rustam-alijanovich": "famousGraduateDetailIbragimovRustamBody",
};
