/** English fallbacks: Fine and applied arts club (`topNav` namespace). */

export const FINE_APPLIED_ARTS_CLUB_DEFAULTS = {
  fineAppliedArtsClubPageTitle: "Fine and applied arts club",
  fineAppliedArtsClubPageBody: `Organizing meaningful leisure activities for youth, guiding them toward professions, and shaping their aesthetic taste are among the top priorities of the educational process. The “Fine and applied arts” club, established at the Termez University of Economics and Service, is a creative haven that fosters not only artistic skills but also patience, taste, and industriousness in students.

One of the most important directions of the club’s activities is painting. Here, students master practical skills alongside the theoretical foundations of fine arts. They are taught step-by-step the harmony of colors, composition building, the laws of light and shadow, and the secrets of portrait and landscape painting. Young creators learn to embody the world of their imagination using simple paper and paint. Every painting is not just an image, but an expression of the young soul’s inner feelings, dreams, and outlook on life. During the lessons, the club leader, Madina Jurayeva, encourages each student to think independently and find their own style, taking into account their individual abilities.

“The club has been operating since 2024. To date, more than 200 graduates have completed the course and been awarded special certificates. The club’s activities harmonize national traditions with modern trends. In particular, straw art lessons cultivate patience and refined taste in students. Ordinary pieces of straw turn into elegant landscapes, national patterns, or decorative compositions under skillful hands. This process educates youth in a spirit of respect for the rich heritage of applied arts. Additionally, one of the modern directions—resin art—is also included in the club’s program. Students learn to create various decorative items, souvenirs, and ornaments using transparent resin. Products created with a blend of colors, dried flowers, glittery elements, and various shapes are bright examples of modern taste and a creative approach,” says Madina Jurayeva.

The club also functions as a small production workshop. Here, students master the secrets of making diadems, various jewelry, bracelets, earrings, and other decorative accessories. Every item is created through a meticulously planned process, from the initial design to the finished product. These activities, which are especially interesting for female students, develop entrepreneurial skills along with shaping aesthetic taste. In fact, some graduates manage commercial pages on social media, selling their handmade items and earning their first income. Such results clearly demonstrate both the spiritual and practical significance of the club. The creative works prepared by the graduates deserve special attention, as they blend national spirit, modern design, and personal style.

“Our main goal in attending the club is not just making objects, but finding mental relaxation and increasing our self-confidence. Here, we learn not only art but also life skills. Working in a team, respecting each other’s opinions, positive thinking, completing every task with high taste, feeling responsibility, and waiting for the result with patience—all of these are formed during the creative process,” says club member Jasmina Begmatova.

The heart of every student who connects with art becomes refined, their taste elevated, and their thinking broadened. The “Fine and applied arts” club operates effectively in nurturing such a well-rounded generation. In conclusion, this club is not just a set of lessons; it is a true school of creativity where talents mature, dreams take flight, and the path to success opens through hard work.`,
  fineAppliedArtsClubHeroSrc: "/images/community-clubs/fine-and-applied-arts-club.png",
} as const;
