/** English fallbacks for Student life → Health support service (`topNav` namespace). */

export const HEALTH_SUPPORT_PAGE_DEFAULTS = {
  healthSupportPageTitle: "Integrated Health, Wellbeing and Support Services at TUES",
  healthSupportPageIntro:
    "Termez University of Economics and Service (TUES) maintains an integrated campus-based health and wellbeing support system designed to protect student and staff welfare, promote early intervention, and ensure continuity of learning through accessible medical, psychological, and inclusive support services. At the centre of this system is the TUES Medical Hub, which functions as the university’s primary on-campus healthcare facility and student wellbeing centre. The university’s public institutional structure also identifies Health Service provision and a dedicated disability-related support environment as part of student life services, while campus materials further confirm the role of the Psychological Support Center and the presence of the TISU MED HUB within the university support framework.",
  healthSupportPhysicalHeading: "Physical Healthcare Services",
  healthSupportPhysicalBody:
    "TUES provides physical healthcare services on campus through the TUES Medical Hub, a permanently operating university medical facility established to deliver immediate and continuous medical assistance to students and staff. The Medical Hub is equipped to provide first-response and primary healthcare support, including general medical consultations, examination and assessment, treatment of minor injuries and illnesses, first aid, basic diagnostics, preventive care, health monitoring, and referral coordination with external hospitals and specialised clinics where higher-level treatment is required. Its permanent campus presence strengthens institutional safety, reduces delays in treatment, and supports a secure academic environment in which urgent and routine health needs can be addressed without disrupting the educational process. The existence of formal Health Service provision and public reference to the TISU MED HUB on the university website reinforce that healthcare support is institutionally embedded within campus life.",
  healthSupportReproductiveHeading: "Sexual and Reproductive Health Support",
  healthSupportReproductiveBody:
    "TUES also addresses sexual and reproductive health within its wider student wellbeing framework. In addition to general healthcare consultations available through the Medical Hub, the university supports awareness-building, guidance, and educational activities related to reproductive health and responsible health behaviour. Official campus materials confirm that the Psychological Support Center regularly conducts seminars, round tables, and awareness activities that include reproductive health and medical culture among the covered themes. This approach allows TUES to address reproductive wellbeing not only through health information and preventive education, but also through early consultation and referral pathways where students require additional medical or specialist support. Students and staff are therefore able to access a campus environment in which reproductive health is acknowledged as a legitimate component of overall wellbeing and preventive care.",
  healthSupportMentalHeading: "Mental Health Support for Students and Staff",
  healthSupportMentalBody:
    "Mental health support is an established part of the TUES support ecosystem. The university’s Psychological Support Center delivers regular interventions aimed at strengthening emotional wellbeing, resilience, and healthy social functioning among members of the university community. According to the university’s published materials, these activities include seminars and discussions on stress management, healthy thinking, family and social wellbeing, and related personal development themes, with active participation by students, teachers, and staff. This confirms that mental health support at TUES is not limited to students alone, but extends to employees as well, making it a whole-of-campus wellbeing function. In practice, this support contributes to improved adjustment to university life, reduced psychosocial pressure, and a more stable and supportive learning and working environment.",
  healthSupportInclusiveHeading: "Inclusive Access and Additional Support",
  healthSupportInclusiveBody:
    "The university’s health and wellbeing model is complemented by inclusive support measures for persons with disabilities and for students requiring additional assistance. TUES publicly describes a range of accessibility and support arrangements, including adapted sanitary facilities, ramps, designated access points, mapped accessible spaces, sign language support for students with hearing impairments, and specialised academic support based on individual needs. The university also reports the use of assistive computer technologies for visually impaired students and structured academic assistance intended to promote equal participation in the educational process. These arrangements show that health and wellbeing support at TUES is understood broadly: it is not confined to treatment alone, but includes physical accessibility, academic continuity, dignity, participation, and barrier reduction across campus life.",
  healthSupportCapacityHeading: "Service Capacity and Institutional Reach",
  healthSupportCapacityBody:
    "The operational scale of this support system demonstrates its institutional importance. Based on the institutional service profile provided for the Medical Hub, the facility operates on a 24/7 basis throughout the academic year and recorded more than 11,000 student visits in the most recent reporting year. This service volume reflects sustained utilisation of campus healthcare infrastructure and indicates that the Medical Hub is used not merely as an emergency point, but as a routine and trusted access point for consultations, urgent care, preventive interventions, follow-up visits, and referral support. When considered together with university-based psychological programming and inclusive campus accommodations, these figures show that TUES has developed a health and wellbeing system with both operational depth and practical reach.",
  healthSupportCoreHeading: "Core Functions and Activities",
  healthSupportCoreBody:
    "Within a single institutional framework, TUES therefore provides: immediate and routine physical healthcare through the Medical Hub; health monitoring and first-response medical support; preventive care and health education; sexual and reproductive health awareness and guidance; mental health and psychosocial support for students and staff; referral coordination for advanced medical needs; accessibility and accommodation measures for students with disabilities; and awareness-building activities that promote resilience, safety, responsible health behaviour, and inclusive participation. Official TUES materials show that these services are embedded in the student life structure of the university and supported by dedicated health, psychological, and accessibility-oriented service elements on campus.",
  healthSupportSignificanceHeading: "Institutional Significance",
  healthSupportSignificanceBody:
    "Taken together, these services demonstrate that TUES does not treat student health as a narrow clinical matter, but as a strategic component of academic success, campus safety, student retention, and institutional responsibility. The presence of an on-campus Medical Hub, structured mental health programming, reproductive health awareness activities, and inclusive support mechanisms creates a comprehensive support environment in which students and staff can access assistance across physical, emotional, and practical dimensions of wellbeing. This integrated model strengthens the resilience of the university community and supports TUES in aligning its student support infrastructure with contemporary higher education expectations for accessibility, wellbeing, and responsible campus care.",
} as const;
