/** English fallbacks for About → Student Council (`topNav` namespace). */

export const STUDENT_COUNCIL_PAGE_DEFAULTS = {
  studentCouncilPageTitle: "Termez University of Economics and Service Student Council",
  studentCouncilPageIntro:
    "Today, the formation of a student self-governance system in higher education institutions is an integral part of building a democratic society.\n\nThe Student Council is a body of student self-governance, whose main task is to protect the interests of young people, increase their social activity and ensure their active participation in the educational process. Although the Council does not have legal entity status, it operates on the principles of independence, transparency, democracy, and legality. This indicates that elements of civil society are being practically implemented at the university.\n\nThe Council conducts its activities in accordance with the Constitution of the Republic of Uzbekistan, the Laws “On Education” and “On State Youth Policy”, as well as the University's Charter, Internal Regulations, and Code of Ethics. This legal foundation ensures the legality and effectiveness of the Council's decisions.\n\nAccording to the Charter, the scope of the Council's responsibilities is extremely broad. In addition to protecting students' rights and establishing effective communication with the university administration, the Council develops proposals to improve the quality of education, organising academic, cultural, sporting and social events, and strengthening discipline and moral education. It is particularly noteworthy that assisting students from low-income and socially vulnerable backgrounds is also established as one of the Council's priority tasks. This demonstrates that the Council has not only an administrative but also a social significance.\n\nFurthermore, organising volunteer activities and developing students' leadership, organisational, and communication skills are also noted as a separate task.\n\nThese areas confirm that the modern education system is aimed at developing not only academic knowledge but also life skills in its students.",
  studentCouncilOrganisationalStructureTitle: "Organisational Structure",
  studentCouncilOrganisationalStructureBody:
    "The Council's organisational structure is built on a clear hierarchy.\n\nThe Council is composed of a chair, two vice-chairs, a secretary, committee heads, faculty representatives, and ordinary members. The chair is elected from among the students for a one-year term, which ensures a turnover of power and the continuous influx of new ideas.\n\nSix permanent committees operate under the Council: Education Quality and Scientific Activities, Cultural and Educational Affairs, Sport and Healthy Lifestyle, Social Issues and Volunteering, Information and Public Relations, and Discipline and Control. Each committee has its own area of focus, which serves to cover all aspects of student life. Furthermore, it is envisaged that a separate student council will be established in each faculty, and the chairs of the faculty councils are automatically considered members of the university Student Council. This vertical communication system ensures that decisions are communicated promptly to the lower level.",
  studentCouncilDecisionMakingTitle: "Decision-making Mechanism",
  studentCouncilDecisionMakingBody:
    "The Council's decision-making procedure is developed on the basis of democratic principles. Meetings are held at least once a month and are quorate with the attendance of at least two-thirds of the members.\n\nDecisions are made by a simple majority vote, and in the event of a tie, the chair's vote is decisive. This procedure guarantees the transparency and fairness of the decision-making process.\n\nA key aspect is that the Council's decisions are advisory for all students at the university. However, decisions reached in agreement with the university administration are binding.\n\nThis approach serves to enhance the Council's effectiveness whilst preserving its independence.",
  studentCouncilMembershipTitle: "Membership: Rights and Responsibilities",
  studentCouncilMembershipBody:
    "The Council's membership is composed of active students with satisfactory academic standing and no disciplinary sanctions.\n\nHowever, membership is not guaranteed indefinitely — a member who is absent from three consecutive meetings without a valid reason, acts in contravention of the Council's decisions, or breaches the university's internal regulations may be removed from the Council.\n\nThis procedure is designed to increase the accountability of Council members and to maintain a high standard of performance.\n\nCouncil members have rights such as voting, standing for election, proposing motions, and participating in meetings with the university's leadership.\n\nOn the other hand, they also undertake obligations such as complying with the Charter, regularly attending meetings, and upholding the university's reputation.",
  studentCouncilCollaborationTitle: "Collaboration and Funding",
  studentCouncilCollaborationBody:
    "The Council is not a closed system — it operates in partnership with the Uzbekistan Youth Union, the university trade union, faculty deanships, student councils of other higher education institutions, local authorities, and non-governmental non-profit organisations. This extensive cooperation significantly expands the Council's capabilities.\n\nA clear funding structure is also in place: the Council's activities are supported by the university budget, sponsorship and charitable funds, grant projects, and other sources not prohibited by law. A strict accountability for every penny is stipulated, ensuring the principles of transparency and responsibility are put into practice.\n\nThe Council submits a quarterly report on its activities to the university's management, and the Chair publishes the annual report at the General Student Assembly. Additionally, information regarding the Council's activities is made public via the university's official website and social media. This multi-tiered accountability system serves to ensure the transparency of the Council's activities and the trust of the student body.",
  studentCouncilClosing:
    "The establishment of the Student Council at the Termez University of Economics and Service and the adoption of its Charter is a significant step in creating a modern, democratic, and student-centred educational environment. The Council's well-thought-out structure, broad remit, democratic decision-making mechanism, and multifaceted collaborative relationships make it not just an official body, but a tool for qualitatively transforming student life.",
} as const;
