/** English fallbacks for About → Women's Affairs Advisory Committee (`topNav` namespace). */

export const WOMENS_AFFAIRS_PAGE_DEFAULTS = {
  womensAffairsPageTitle:
    "Women's Affairs Advisory Committee at the University of Economics and Services in Termez",
  womensAffairsPageBody:
    "The University of Economics and Services in Termez has established an Advisory Committee on women's affairs, which supports women at a social and political level.\n\nThe Committee is a standing, public body designed to protect the rights and legitimate interests of women, as well as to assist in the implementation of the socio-political guarantees provided for in the Constitution and laws of the Republic of Uzbekistan.\n\nThe Council's activities are based on the Constitution and laws of the Republic of Uzbekistan, decisions of the chambers of the Oliy Majlis of the Republic of Uzbekistan, decrees, resolutions and directives of the President of the Republic of Uzbekistan and resolutions and directives of the Cabinet of Ministers of the Republic of Uzbekistan, as well as the Ministry of Science and Innovation, the normative documents of the Ministry of Higher Education, Science and Innovation, in accordance with this Regulation and other legislative acts.\n\nAt the same time, its activities are conducted on the principles of legality, collective decision-making, transparency, mutual cooperation and respect, equality, voluntariness, and taking public opinion into account.",
  womensAffairsPageTasksHeading: "The main tasks and functions of the Council are as follows:",
  womensAffairsPageTasksBullets:
    "- To coordinate the organisational work aimed at ensuring the effective implementation of state policy to support women, protecting their rights and legitimate interests, and increasing their role and active participation in the country's socio-political life;\n- Assisting in the organisation of targeted events aimed at strengthening the role of women in the labour market, the public sector and civil service, providing them with social and legal support, and systematically monitoring their feedback;\n- To identify in a timely manner the problems faced by women in the labour market; to assist in the organisation of targeted initiatives aimed at strengthening the role of women in the public sector and public administration; to provide systematic social and legal support; to compile a register of women in need of assistance and to provide them, including women with disabilities, with social, legal, psychological and material support;\n- Assisting in the creation of a targeted list for women with disabilities, providing them with social, legal, psychological and material support, and supplying them with rehabilitation equipment;\n- To conduct public oversight of the enforcement of laws ensuring equal rights and opportunities for men and women, and to make relevant recommendations;\n- To monitor the implementation of laws protecting women from violence and harassment, and to submit well-considered recommendations to ministries to identify victims of violence, promote their rehabilitation, and assist in the protection of their rights;\n- Participating in the development and implementation of regional plans to protect women from hooliganism and violence;\n- To assist in preparing female students for family life, to encourage young families to participate in social activities, and to widely promote the lives and lifestyles of exemplary women engaged in social and humanitarian work;\n- Organising various competitions and sporting events among women, as well as conducting the selection process for candidates for the “Zulfiya National Award” and the “Honourable Woman” medal under effective public supervision, with the aim of ensuring compliance with the principles of legality, social justice and transparency;\n- To ensure the implementation and direct compliance with the documents, standards, and requirements established in national and international legislation on the protection of women's rights;\n- Nominate outstanding female employees within the system for consideration as candidates for national awards.",
} as const;
